server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_read_timeout 10s;
    }
    location /maplibre/ {
        types { application/javascript mjs; }
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
